### PR TITLE
Fix transaction time mapping

### PR DESCRIPTION
**Pull request by patiee**
Time in Transaction is expected to be a string, so it shouldn't be returned as object.

### CODE REVIEW

**Review by pacmessica — APPROVED** [review]
lgtm. could you double check that there's no issues with time in any of the other responses? Thanks again!

what linter are you using? :P

**Comment by patiee** [comment]
i use [this one](https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter) for vscode :D but i need to change it, what linter are you using? 

I checked time for Block also, but time in a Block is expected to be an object.

**Comment by patiee** [comment]
in the Header struct of Block time is ` *timestamp.Timestamp`, but in Transaction time is a string

**Comment by pacmessica** [comment]
yeah, I'm not a fun of the inconsistency wrt timestamp and string. I'll create a ticket- it might require changes in the indexer too, so I'd say it's not high priority right now. 

no more [object object] issues?

**Comment by patiee** [comment]
I found some on in response from ChainService on `getStatus`

status.nodeProperties.registry is `'[object Object]'`

**Comment by pacmessica** [comment]
> I found one in response from ChainService on `getStatus`
> 
> status.nodeProperties.registry is `'[object Object]'`

interesting! let's see what pawel says

https://www.notion.so/figmentnetworks/b47c0f8b935741d8ac28717ddeea2038?v=5e4e1d3854094b788ae2b612329f27e8&p=02d54a5329fa40f1a36091b1df405fa1

**Pull request merged**
